import React, { useEffect, useMemo, useState } from "react";
import "./Groups.css";

const API_URL = (import.meta.env.VITE_API_URL || "/api").replace(/\/$/, "");
const adminToken = () => localStorage.getItem("access_token") || sessionStorage.getItem("access_token") || localStorage.getItem("adminToken") || sessionStorage.getItem("adminToken") || "";
const studentToken = () => localStorage.getItem("student_token") || sessionStorage.getItem("student_token") || "";
const headers = (json=false) => ({ Accept:"application/json", ...(json ? {"Content-Type":"application/json"}:{}), Authorization:`Bearer ${adminToken() || studentToken()}` });

export default function Groups({ role="student" }) {
  const isAdmin = role === "admin";
  const [groups,setGroups]=useState([]); const [users,setUsers]=useState([]); const [selected,setSelected]=useState(null); const [messages,setMessages]=useState([]); const [tab,setTab]=useState("messages");
  const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [text,setText]=useState("");
  const [showCreate,setShowCreate]=useState(false); const [showInvite,setShowInvite]=useState(false); const [showResource,setShowResource]=useState(false);
  const [form,setForm]=useState({name:"",description:"",chatMode:"everyone",chatMemberIds:[]}); const [inviteIds,setInviteIds]=useState([]); const [inviteRole,setInviteRole]=useState("member");
  const [resource,setResource]=useState({type:"notes",title:"",content:""}); const [audience,setAudience]=useState("everyone"); const [recipientIds,setRecipientIds]=useState([]);

  const load = async()=>{ try { setError(""); const [g,u]=await Promise.all([fetch(`${API_URL}/api/groups`,{headers:headers()}),fetch(`${API_URL}/api/community/users`,{headers:headers()})]); const gd=await g.json(); const ud=await u.json(); if(!g.ok) throw new Error(gd.message||"Unable to load groups"); setGroups(gd.groups||[]); setUsers(ud.users||[]); if(selected){ const fresh=(gd.groups||[]).find(x=>x.id===selected.id); if(fresh)setSelected(fresh); } } catch(e){setError(e.message||"Unable to load groups")} };
  const loadMessages = async(id)=>{ if(!id)return; const r=await fetch(`${API_URL}/api/groups/${id}/messages`,{headers:headers()}); const d=await r.json(); if(r.ok)setMessages(d.messages||[]); };
  useEffect(()=>{load()},[]); useEffect(()=>{if(selected)loadMessages(selected.id)},[selected?.id]);
  const members = selected?.members||[]; const selectableUsers=useMemo(()=>users.filter(u=>!members.some(m=>String(m.userId)===String(u.id))),[users,members]);
  const updateForm=(k,v)=>setForm(f=>({...f,[k]:v}));
  const createGroup=async(e)=>{e.preventDefault();setBusy(true);try{const r=await fetch(`${API_URL}/api/groups`,{method:"POST",headers:headers(true),body:JSON.stringify(form)});const d=await r.json();if(!r.ok)throw new Error(d.message||"Could not create group");setGroups(g=>[d.group,...g]);setSelected(d.group);setShowCreate(false);setForm({name:"",description:"",chatMode:"everyone",chatMemberIds:[]})}catch(e){setError(e.message)}finally{setBusy(false)}};
  const invite=async()=>{if(!selected||!inviteIds.length)return;setBusy(true);try{const r=await fetch(`${API_URL}/api/groups/${selected.id}/invites`,{method:"POST",headers:headers(true),body:JSON.stringify({userIds:inviteIds,role:inviteRole})});const d=await r.json();if(!r.ok)throw new Error(d.message||"Invite failed");setShowInvite(false);setInviteIds([]);alert(`${d.invitedCount||0} invitation(s) sent.`)}catch(e){setError(e.message)}finally{setBusy(false)}};
  const addResource=async(e)=>{e.preventDefault();if(!selected)return;setBusy(true);try{const r=await fetch(`${API_URL}/api/groups/${selected.id}/resources`,{method:"POST",headers:headers(true),body:JSON.stringify(resource)});const d=await r.json();if(!r.ok)throw new Error(d.message||"Could not add resource");setSelected(d.group);setShowResource(false);setResource({type:"notes",title:"",content:""})}catch(e){setError(e.message)}finally{setBusy(false)}};
  const send=async(e)=>{e.preventDefault();if(!selected||!text.trim())return;const r=await fetch(`${API_URL}/api/groups/${selected.id}/messages`,{method:"POST",headers:headers(true),body:JSON.stringify({body:text,audience,recipientIds})});const d=await r.json();if(!r.ok){setError(d.message||"Message failed");return}setMessages(m=>[...m,d.message]);setText("");setAudience("everyone");setRecipientIds([])};
  const toggle=(arr,setter,id)=>setter(arr.includes(id)?arr.filter(x=>x!==id):[...arr,id]);
  return <div className="community-page groups-page">
    <div className="community-heading"><div><span className="community-kicker">COMMUNITY</span><h1>Groups</h1><p>WhatsApp-style class groups for messages, timetable, notes and assignments.</p></div>{isAdmin&&<button className="community-primary" onClick={()=>setShowCreate(true)}>＋ Create Group</button>}</div>
    {error&&<div className="community-error">{error}</div>}
    <div className="groups-layout"><aside className="groups-list"><div className="community-section-title">Your Groups <span>{groups.length}</span></div>{groups.map(g=><button key={g.id} className={`group-list-item ${selected?.id===g.id?"selected":""}`} onClick={()=>{setSelected(g);setTab("messages")}}><span className="group-avatar">{g.name.slice(0,1).toUpperCase()}</span><span><strong>{g.name}</strong><small>{g.members?.length||0} members</small></span></button>)}{!groups.length&&<div className="empty-state">No groups yet.</div>}</aside>
      <section className="group-workspace">{!selected?<div className="empty-workspace"><div>◉</div><h2>Select a group</h2><p>Choose a group from the left to open its community.</p></div>:<>
        <div className="group-header"><div><h2>{selected.name}</h2><p>{selected.description||"Class community"} · {members.length} members</p></div><div className="group-header-actions">{selected.canAdmin&&<><button onClick={()=>setShowInvite(true)}>＋ Add Members</button><button onClick={()=>setShowResource(true)}>＋ Resource</button></>}</div></div>
        <div className="group-tabs">{["messages","timetable","notes","assignments"].map(t=><button className={tab===t?"active":""} key={t} onClick={()=>setTab(t)}>{t[0].toUpperCase()+t.slice(1)}</button>)}</div>
        {tab==="messages"&&<><div className="message-list">{messages.map(m=><div className={`community-message ${m.senderId===selected.createdBy?"admin-message":""}`} key={m.id}><div className="message-meta"><strong>{m.sender?.name||"User"}</strong><span>{new Date(m.createdAt).toLocaleString()}</span>{m.audience!=="everyone"&&<em>{m.audience}</em>}</div><p>{m.body}</p></div>)}{!messages.length&&<div className="empty-state">No messages yet.</div>}</div><form className="group-compose" onSubmit={send}><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Write a group message..."/><div className="compose-controls"><select value={audience} onChange={e=>setAudience(e.target.value)} disabled={!selected.canAdmin}><option value="everyone">Everyone can view</option><option value="admins">Admins only</option><option value="selected">Selected members</option></select>{audience==="selected"&&<select multiple value={recipientIds} onChange={e=>setRecipientIds([...e.target.selectedOptions].map(o=>o.value))}>{members.filter(m=>m.user).map(m=><option key={m.userId} value={m.userId}>{m.user.name}</option>)}</select>}<button className="community-primary" disabled={!text.trim()}>Send</button></div>{!selected.canChat&&<small className="muted">Chat is currently restricted to admins or selected members.</small>}</form></>}
        {tab!=="messages"&&<div className="resource-grid">{(selected.resources?.[tab]||[]).map(item=><article className="resource-card" key={item.id}><span>{tab.slice(0,-1).toUpperCase()}</span><h3>{item.title}</h3><p>{item.content}</p><small>{new Date(item.createdAt).toLocaleString()}</small></article>)}{!(selected.resources?.[tab]||[]).length&&<div className="empty-state">No {tab} added yet.</div>}</div>}
      </>}</section></div>
    {showCreate&&<div className="modal-backdrop"><form className="community-modal" onSubmit={createGroup}><h2>Create Group</h2><input placeholder="Group name" value={form.name} onChange={e=>updateForm("name",e.target.value)} required/><textarea placeholder="Description" value={form.description} onChange={e=>updateForm("description",e.target.value)}/><label>Who can chat?</label><select value={form.chatMode} onChange={e=>updateForm("chatMode",e.target.value)}><option value="everyone">Everyone</option><option value="admins">Admins only</option><option value="selected">Selected members</option></select>{form.chatMode==="selected"&&<select multiple value={form.chatMemberIds} onChange={e=>updateForm("chatMemberIds",[...e.target.selectedOptions].map(o=>o.value))}>{users.filter(u=>u.role==="student").map(u=><option key={u.id} value={u.id}>{u.name} {u.studentId?`(${u.studentId})`:""}</option>)}</select>}<div className="modal-actions"><button type="button" onClick={()=>setShowCreate(false)}>Cancel</button><button className="community-primary" disabled={busy}>Create</button></div></form></div>}
    {showInvite&&<div className="modal-backdrop"><div className="community-modal"><h2>Invite to {selected?.name}</h2><label>Invite as</label><select value={inviteRole} onChange={e=>setInviteRole(e.target.value)}><option value="member">Member</option><option value="admin">Admin</option></select><select multiple value={inviteIds} onChange={e=>setInviteIds([...e.target.selectedOptions].map(o=>o.value))}>{selectableUsers.map(u=><option key={u.id} value={u.id}>{u.name} — {u.role}{u.studentId?` — ${u.studentId}`:""}</option>)}</select><div className="modal-actions"><button onClick={()=>setShowInvite(false)}>Cancel</button><button className="community-primary" onClick={invite} disabled={!inviteIds.length||busy}>Send Invitation</button></div></div></div>}
    {showResource&&<div className="modal-backdrop"><form className="community-modal" onSubmit={addResource}><h2>Add Group Resource</h2><select value={resource.type} onChange={e=>setResource(r=>({...r,type:e.target.value}))}><option value="timetable">Timetable</option><option value="notes">Notes</option><option value="assignments">Assignments</option></select><input placeholder="Title" value={resource.title} onChange={e=>setResource(r=>({...r,title:e.target.value}))} required/><textarea placeholder="Details / link / instructions" value={resource.content} onChange={e=>setResource(r=>({...r,content:e.target.value}))} required/><div className="modal-actions"><button type="button" onClick={()=>setShowResource(false)}>Cancel</button><button className="community-primary" disabled={busy}>Add</button></div></form></div>}
  </div>;
}
