import React, { useEffect, useState } from "react";
import "./Notifications.css";
const API_URL=(import.meta.env.VITE_API_URL||"http://localhost:5000").replace(/\/$/,"");
const token=()=>localStorage.getItem("access_token")||sessionStorage.getItem("access_token")||localStorage.getItem("student_token")||sessionStorage.getItem("student_token")||"";
const headers=(json=false)=>({Accept:"application/json",...(json?{"Content-Type":"application/json"}:{}),Authorization:`Bearer ${token()}`});
export default function Notifications(){const [items,setItems]=useState([]);const [invites,setInvites]=useState([]);const [error,setError]=useState("");
const load=async()=>{try{const [n,i]=await Promise.all([fetch(`${API_URL}/api/notifications`,{headers:headers()}),fetch(`${API_URL}/api/group-invites`,{headers:headers()})]);const nd=await n.json();const id=await i.json();if(!n.ok)throw new Error(nd.message||"Unable to load notifications");setItems(nd.notifications||[]);setInvites(id.invites||[])}catch(e){setError(e.message||"Unable to load notifications")}};
useEffect(()=>{load()},[]);
const mark=async id=>{await fetch(`${API_URL}/api/notifications/${id}/read`,{method:"POST",headers:headers(true)});setItems(x=>x.map(n=>n.id===id?{...n,read:true}:n))};
const respond=async(id,action)=>{const r=await fetch(`${API_URL}/api/group-invites/${id}/${action}`,{method:"POST",headers:headers(true)});if(r.ok){setInvites(x=>x.filter(i=>i.id!==id));load()}};
const icon=t=>t==="GROUP_INVITE"?"👥":t==="PRIVATE_MESSAGE"?"✉":t==="GROUP_MESSAGE"?"💬":t==="RESULT"?"✓":t==="TEST"?"📝":"•";
return <div className="notifications-page"><div className="community-heading"><div><span className="community-kicker">ACTIVITY CENTER</span><h1>Notifications</h1><p>Invitations, tests, results and private-message alerts.</p></div><button className="notification-clear" onClick={async()=>{await fetch(`${API_URL}/api/notifications/read-all`,{method:"POST",headers:headers(true)});setItems(x=>x.map(n=>({...n,read:true})))}}>Mark all read</button></div>{error&&<div className="community-error">{error}</div>}{invites.length>0&&<section className="notification-section"><h2>Group Invitations</h2>{invites.map(i=><div className="notification-card invite" key={i.id}><div className="notification-icon">👥</div><div className="notification-body"><strong>{i.group?.name||"Group invitation"}</strong><p>You were invited as {i.role}.</p><div className="notification-actions"><button onClick={()=>respond(i.id,"accept")}>Accept</button><button onClick={()=>respond(i.id,"decline")}>Decline</button></div></div></div>)}</section>}{<section className="notification-section"><h2>Notifications</h2>{items.map(n=><button key={n.id} className={`notification-card ${n.read?"read":"unread"}`} onClick={()=>!n.read&&mark(n.id)}><div className="notification-icon">{icon(n.type)}</div><div className="notification-body"><strong>{n.title}</strong><p>{n.message}</p><small>{new Date(n.createdAt).toLocaleString()}</small></div>{!n.read&&<span className="unread-dot"/>}</button>)}{!items.length&&<div className="empty-notifications">You're all caught up.</div>}</section>}</div>}
